// ErisNote-Vue/pages/register/index.vue
<template>
  <div class="flex flex-col items-center justify-center h-screen">
    <div class="box rounded-2xl p-48 pb-32 border-2">
      <div class="flex">
        <div class="text-4xl pb-12">ErisNote Register</div>
      </div>
      <mdui-text-field :value="form.username" class="my-2" label="用户名" variant="outlined"
                       @input="form.username = $event.target.value"/>
      <mdui-text-field :value="form.password" class="my-2" label="密码" type="password"
                       variant="outlined"
                       @input="form.password = $event.target.value"/>
      <mdui-text-field :value="form.confirmPassword" class="my-2" label="确认密码" type="password"
                       variant="outlined"
                       @input="form.confirmPassword = $event.target.value"/>

      <div class="flex justify-center">
        <mdui-button class="mt-12" @click="registerHandler">提交</mdui-button>
      </div>
    </div>
  </div>
</template>

<script setup>
definePageMeta({
  layout: 'none'
})


const form = ref({
  username: "",
  password: "",
  confirmPassword: ""
})

const registerHandler = async() => {
  if (form.value.password !== form.value.confirmPassword) {
    alert("密码不一致")
    return
  }
  const resp = await api.userController.register({
    body:{
      username: form.value.username,
      password: form.value.password
    }
  })

  if (resp.code!==200){
    const msg="注册失败"
    alert(msg)
    console.log(msg+": "+resp.msg)
  }else {
    alert("注册成功")
    navigateTo("/")
  }
}

</script>

<style scoped>
.box {
  background-color: rgb(var(--mdui-color-secondary-container));
  border-color: rgb(var(--mdui-color-primary));
}
</style>

// front/app/register/page.tsx
"use client";
import { api } from "@/api/ApiInstance";
import { Button, Icon, IconButton, TextField } from "actify";
import { useRouter } from "next/navigation";
import { MouseEvent, useState } from "react";

export default function RegisterPage() {
  const router = useRouter();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [passwordConfirm, setPasswordConfirm] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const passwordShowToggle = (event: MouseEvent<HTMLButtonElement>) => {
    event.preventDefault();
    setShowPassword((prev) => !prev);
  };

  const handleRegister = async () => {
    if (password !== passwordConfirm) {
      alert("两次密码不一致");
      return;
    }

    const res = await api.userController.register({
      body: {
        username: username,
        password: password,
      },
    });

    if (res.code !== 200) {
      alert("注册失败");
      console.log(res.msg);
      return;
    }

    router.push("/");
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <div className="bg-surface-variant  rounded-2xl border-2 border-surface-dim shadow-lg p-20">
        <h1 className="text-3xl text-center">注册到 ErisNote</h1>

        <div className="flex flex-col gap-4 p-20">
          <TextField
            label="用户名"
            variant="outlined"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
          >
            <TextField.LeadingIcon>
              <Icon>Account_Circle</Icon>
            </TextField.LeadingIcon>
          </TextField>
          <TextField
            label="密码"
            variant="outlined"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            type={showPassword ? "text" : "password"}
          >
            <TextField.LeadingIcon>
              <Icon>lock</Icon>
            </TextField.LeadingIcon>
            <TextField.TrailingIcon>
              <IconButton onClick={passwordShowToggle}>
                <Icon>{showPassword ? "visibility_off" : "visibility"}</Icon>
              </IconButton>
            </TextField.TrailingIcon>
          </TextField>
          <TextField
            label="确认密码"
            variant="outlined"
            value={passwordConfirm}
            onChange={(e) => setPasswordConfirm(e.target.value)}
            type={showPassword ? "text" : "password"}
          >
            <TextField.LeadingIcon>
              <Icon>lock</Icon>
            </TextField.LeadingIcon>
            <TextField.TrailingIcon>
              <IconButton onClick={passwordShowToggle}>
                <Icon>{showPassword ? "visibility_off" : "visibility"}</Icon>
              </IconButton>
            </TextField.TrailingIcon>
          </TextField>
        </div>

        <div className="flex flex-row items-center justify-center gap-4">
          <Button onClick={handleRegister}>注册</Button>
          <Button
            onClick={() => {
              router.push("/login");
            }}
          >
            返回登陆
          </Button>
        </div>
      </div>
    </div>
  );
}
